import { Type } from '@angular/core';
import { Route } from '@angular/router';

import { CURRICULUM } from './curriculum';

const DEMO_LOADERS: Record<string, () => Promise<Type<unknown>>> = {
  'lifecycle': () => import('../pages/01-lifecycle-demo/lifecycle-demo').then((m) => m.LifecycleDemo),
  'onpush': () => import('../pages/02-onpush-demo/onpush-demo').then((m) => m.OnpushDemo),
  'cdr': () => import('../pages/03-cdr-demo/cdr-demo').then((m) => m.CdrDemo),
  'zoneless': () => import('../pages/04-zoneless-demo/zoneless-demo').then((m) => m.ZonelessDemo),
  'zone': () => import('../pages/05-zone-demo/zone-demo').then((m) => m.ZoneDemo),
  'inject': () => import('../pages/06-inject-demo/inject-demo').then((m) => m.InjectDemo),
  'injectors': () => import('../pages/07-injectors-demo/injectors-demo').then((m) => m.InjectorsDemo),
  'providers': () => import('../pages/08-providers-demo/providers-demo').then((m) => m.ProvidersDemo),
  'signals-basics': () => import('../pages/09-signals-basics-demo/signals-basics-demo').then((m) => m.SignalsBasicsDemo),
  'signals-advanced': () => import('../pages/10-signals-advanced-demo/signals-advanced-demo').then((m) => m.SignalsAdvancedDemo),
  'signals-components': () => import('../pages/11-signals-components-demo/signals-components-demo').then((m) => m.SignalsComponentsDemo),
  'signals-dom': () => import('../pages/12-signals-dom-demo/signals-dom-demo').then((m) => m.SignalsDomDemo),
  'signals-philosophy': () => import('../pages/13-signals-philosophy-demo/signals-philosophy-demo').then((m) => m.SignalsPhilosophyDemo),
  'rxjs-streams': () => import('../pages/14-rxjs-streams-demo/rxjs-streams-demo').then((m) => m.RxjsStreamsDemo),
  'rxjs-switching': () => import('../pages/15-rxjs-switching-demo/rxjs-switching-demo').then((m) => m.RxjsSwitchingDemo),
  'rxjs-combining': () => import('../pages/16-rxjs-combining-demo/rxjs-combining-demo').then((m) => m.RxjsCombiningDemo),
  'rxjs-memory-leaks': () => import('../pages/17-rxjs-memory-leaks-demo/rxjs-memory-leaks-demo').then((m) => m.RxjsMemoryLeaksDemo),
  'rxjs-theory': () => import('../pages/18-rxjs-theory-demo/rxjs-theory-demo').then((m) => m.RxjsTheoryDemo),
  'standalone-components': () => import('../pages/19-standalone-components-demo/standalone-components-demo').then((m) => m.StandaloneComponentsDemo),
  'standalone-routing': () => import('../pages/20-standalone-routing-demo/standalone-routing-demo').then((m) => m.StandaloneRoutingDemo),
  'routing-guards-data': () => import('../pages/21-routing-guards-data-demo/routing-guards-data-demo').then((m) => m.RoutingGuardsDataDemo),
  'routing-custom': () => import('../pages/22-routing-custom-demo/routing-custom-demo').then((m) => m.RoutingCustomDemo),
  'routing-ux': () => import('../pages/23-routing-ux-demo/routing-ux-demo').then((m) => m.RoutingUxDemo),
  'state-local': () => import('../pages/24-state-local-demo/state-local-demo').then((m) => m.StateLocalDemo),
  'state-global': () => import('../pages/25-state-global-demo/state-global-demo').then((m) => m.StateGlobalDemo),
  'state-concepts': () => import('../pages/26-state-concepts-demo/state-concepts-demo').then((m) => m.StateConceptsDemo),
  'control-flow-core': () => import('../pages/27-control-flow-core-demo/control-flow-core-demo').then((m) => m.ControlFlowCoreDemo),
  'control-flow-advanced': () => import('../pages/28-control-flow-advanced-demo/control-flow-advanced-demo').then((m) => m.ControlFlowAdvancedDemo),
  'defer-basics': () => import('../pages/29-defer-basics-demo/defer-basics-demo').then((m) => m.DeferBasicsDemo),
  'defer-triggers': () => import('../pages/30-defer-triggers-demo/defer-triggers-demo').then((m) => m.DeferTriggersDemo),
  'perf-templates': () => import('../pages/31-perf-templates-demo/perf-templates-demo').then((m) => m.PerfTemplatesDemo),
  'perf-build': () => import('../pages/32-perf-build-demo/perf-build-demo').then((m) => m.PerfBuildDemo),
  'forms-reactive': () => import('../pages/33-forms-reactive-demo/forms-reactive-demo').then((m) => m.FormsReactiveDemo),
  'forms-custom': () => import('../pages/34-forms-custom-demo/forms-custom-demo').then((m) => m.FormsCustomDemo),
  'ssr-modern': () => import('../pages/35-ssr-modern-demo/ssr-modern-demo').then((m) => m.SsrModernDemo),
  'ssr-advanced': () => import('../pages/36-ssr-advanced-demo/ssr-advanced-demo').then((m) => m.SsrAdvancedDemo),
  'ssr-lifecycle': () => import('../pages/37-ssr-lifecycle-demo/ssr-lifecycle-demo').then((m) => m.SsrLifecycleDemo),
  'testing-unit': () => import('../pages/38-testing-unit-demo/testing-unit-demo').then((m) => m.TestingUnitDemo),
  'testing-runners': () => import('../pages/39-testing-runners-demo/testing-runners-demo').then((m) => m.TestingRunnersDemo),
  'testing-integration': () => import('../pages/40-testing-integration-demo/testing-integration-demo').then((m) => m.TestingIntegrationDemo),
  'arch-design': () => import('../pages/41-arch-design-demo/arch-design-demo').then((m) => m.ArchDesignDemo),
  'arch-scale': () => import('../pages/42-arch-scale-demo/arch-scale-demo').then((m) => m.ArchScaleDemo),
  'arch-patterns': () => import('../pages/43-arch-patterns-demo/arch-patterns-demo').then((m) => m.ArchPatternsDemo),
  'arch-relations': () => import('../pages/44-arch-relations-demo/arch-relations-demo').then((m) => m.ArchRelationsDemo),
  'ds-foundation': () => import('../pages/45-ds-foundation-demo/ds-foundation-demo').then((m) => m.DsFoundationDemo),
  'ds-tools': () => import('../pages/46-ds-tools-demo/ds-tools-demo').then((m) => m.DsToolsDemo),
  'ds-custom': () => import('../pages/47-ds-custom-demo/ds-custom-demo').then((m) => m.DsCustomDemo),
  'cicd-standards': () => import('../pages/48-cicd-standards-demo/cicd-standards-demo').then((m) => m.CicdStandardsDemo),
  'cicd-api': () => import('../pages/49-cicd-api-demo/cicd-api-demo').then((m) => m.CicdApiDemo),
  'cicd-infra': () => import('../pages/50-cicd-infra-demo/cicd-infra-demo').then((m) => m.CicdInfraDemo),
  'perf-metrics-ux': () => import('../pages/51-perf-metrics-ux-demo/perf-metrics-ux-demo').then((m) => m.PerfMetricsUxDemo),
  'perf-metrics-monitoring': () => import('../pages/52-perf-metrics-monitoring-demo/perf-metrics-monitoring-demo').then((m) => m.PerfMetricsMonitoringDemo),
  'storage-sync': () => import('../pages/53-storage-sync-demo/storage-sync-demo').then((m) => m.StorageSyncDemo),
  'storage-async-db': () => import('../pages/54-storage-async-db-demo/storage-async-db-demo').then((m) => m.StorageAsyncDbDemo),
  'storage-libraries': () => import('../pages/55-storage-libraries-demo/storage-libraries-demo').then((m) => m.StorageLibrariesDemo),
  'storage-network': () => import('../pages/56-storage-network-demo/storage-network-demo').then((m) => m.StorageNetworkDemo),
  'storage-offline': () => import('../pages/57-storage-offline-demo/storage-offline-demo').then((m) => m.StorageOfflineDemo),
  'storage-security-basics': () => import('../pages/58-storage-security-basics-demo/storage-security-basics-demo').then((m) => m.StorageSecurityBasicsDemo),
  'storage-security-limits': () => import('../pages/59-storage-security-limits-demo/storage-security-limits-demo').then((m) => m.StorageSecurityLimitsDemo),
  'storage-security-arch': () => import('../pages/60-storage-security-arch-demo/storage-security-arch-demo').then((m) => m.StorageSecurityArchDemo),
  'storage-security-tools': () => import('../pages/61-storage-security-tools-demo/storage-security-tools-demo').then((m) => m.StorageSecurityToolsDemo),
  'js-basics': () => import('../pages/62-js-basics-demo/js-basics-demo').then((m) => m.JsBasicsDemo),
  'js-memory': () => import('../pages/63-js-memory-demo/js-memory-demo').then((m) => m.JsMemoryDemo),
  'js-oop': () => import('../pages/64-js-oop-demo/js-oop-demo').then((m) => m.JsOopDemo),
  'js-async': () => import('../pages/65-js-async-demo/js-async-demo').then((m) => m.JsAsyncDemo),
  'browser-rendering-opt': () => import('../pages/66-browser-rendering-opt-demo/browser-rendering-opt-demo').then((m) => m.BrowserRenderingOptDemo),
  'browser-rendering-perf': () => import('../pages/67-browser-rendering-perf-demo/browser-rendering-perf-demo').then((m) => m.BrowserRenderingPerfDemo),
  'http-protocol': () => import('../pages/68-http-protocol-demo/http-protocol-demo').then((m) => m.HttpProtocolDemo),
  'http-browser': () => import('../pages/69-http-browser-demo/http-browser-demo').then((m) => m.HttpBrowserDemo),
  'security-code': () => import('../pages/70-security-code-demo/security-code-demo').then((m) => m.SecurityCodeDemo),
  'security-auth': () => import('../pages/71-security-auth-demo/security-auth-demo').then((m) => m.SecurityAuthDemo),
  'observability-prod': () => import('../pages/72-observability-prod-demo/observability-prod-demo').then((m) => m.ObservabilityProdDemo),
  'api-integration': () => import('../pages/73-api-integration-demo/api-integration-demo').then((m) => m.ApiIntegrationDemo),
  'api-reliability': () => import('../pages/74-api-reliability-demo/api-reliability-demo').then((m) => m.ApiReliabilityDemo),
  'web-components-standards': () => import('../pages/75-web-components-standards-demo/web-components-standards-demo').then((m) => m.WebComponentsStandardsDemo),
  'a11y-basics': () => import('../pages/76-a11y-basics-demo/a11y-basics-demo').then((m) => m.A11yBasicsDemo),
  'build-internals': () => import('../pages/77-build-internals-demo/build-internals-demo').then((m) => m.BuildInternalsDemo),
  'ai-native-dev': () => import('../pages/78-ai-native-dev-demo/ai-native-dev-demo').then((m) => m.AiNativeDevDemo),
  'typescript-advanced': () => import('../pages/79-typescript-advanced-demo/typescript-advanced-demo').then((m) => m.TypescriptAdvancedDemo),
};

export function buildCurriculumRoutes(): Route[] {
  return CURRICULUM.flatMap((group) =>
    group.items.map((item) => ({
      path: item.path,
      loadComponent: DEMO_LOADERS[item.path],
    })),
  );
}
