/* eslint-disable */
/** Generated by scripts/generate-artifacts-manifest.mjs — do not edit manually */
import { ArtifactsManifest } from './artifacts.types';

export const ARTIFACTS_MANIFEST: ArtifactsManifest = {
  "generatedAt": "2026-06-15T12:16:21.007Z",
  "categories": [
    {
      "order": 0,
      "slug": "00-general",
      "title": "Общие материалы",
      "files": []
    },
    {
      "order": 1,
      "slug": "01-angular-core-internals",
      "title": "Angular Core Internals",
      "files": [
        {
          "name": "Angular_Senior_Architecture.pdf",
          "relativePath": "Angular_Senior_Architecture.pdf",
          "url": "artifacts/01-angular-core-internals/Angular_Senior_Architecture.pdf",
          "size": 15128897,
          "extension": "pdf",
          "updatedAt": "2026-06-11T08:34:57.033Z"
        }
      ]
    },
    {
      "order": 2,
      "slug": "02-signals-modern-core",
      "title": "Signals (Modern Core)",
      "files": [
        {
          "name": "Angular_Signals_Evolution.pdf",
          "relativePath": "Angular_Signals_Evolution.pdf",
          "url": "artifacts/02-signals-modern-core/Angular_Signals_Evolution.pdf",
          "size": 16882119,
          "extension": "pdf",
          "updatedAt": "2026-06-15T12:14:16.298Z"
        }
      ]
    },
    {
      "order": 3,
      "slug": "03-rxjs-deep-dive",
      "title": "RxJS (Deep Dive)",
      "files": []
    },
    {
      "order": 4,
      "slug": "04-standalone-architecture",
      "title": "Standalone Architecture",
      "files": []
    },
    {
      "order": 5,
      "slug": "05-routing-advanced",
      "title": "Routing (Advanced)",
      "files": []
    },
    {
      "order": 6,
      "slug": "06-state-management",
      "title": "State Management",
      "files": []
    },
    {
      "order": 7,
      "slug": "07-modern-control-flow",
      "title": "Modern Control Flow",
      "files": []
    },
    {
      "order": 8,
      "slug": "08-deferrable-views",
      "title": "Deferrable Views",
      "files": []
    },
    {
      "order": 9,
      "slug": "09-performance-optimization",
      "title": "Performance Optimization",
      "files": []
    },
    {
      "order": 10,
      "slug": "10-forms-advanced",
      "title": "Forms (Advanced)",
      "files": []
    },
    {
      "order": 11,
      "slug": "11-rendering-ssr",
      "title": "Rendering / SSR",
      "files": []
    },
    {
      "order": 12,
      "slug": "12-testing",
      "title": "Testing",
      "files": []
    },
    {
      "order": 13,
      "slug": "13-architecture-and-monorepos",
      "title": "Architecture & Monorepos",
      "files": []
    },
    {
      "order": 14,
      "slug": "14-design-system",
      "title": "Design System",
      "files": []
    },
    {
      "order": 15,
      "slug": "15-frontend-setup-and-ci-cd",
      "title": "Frontend Setup & CI/CD",
      "files": []
    },
    {
      "order": 16,
      "slug": "16-performance-metrics",
      "title": "Performance Metrics",
      "files": []
    },
    {
      "order": 17,
      "slug": "17-client-side-storage",
      "title": "Client-Side Storage",
      "files": []
    },
    {
      "order": 18,
      "slug": "18-storage-security",
      "title": "Storage Security",
      "files": []
    },
    {
      "order": 19,
      "slug": "19-javascript-core",
      "title": "JavaScript Core",
      "files": []
    },
    {
      "order": 20,
      "slug": "20-browser-rendering",
      "title": "Browser Rendering",
      "files": []
    },
    {
      "order": 21,
      "slug": "21-http-networking",
      "title": "HTTP / Networking",
      "files": []
    },
    {
      "order": 22,
      "slug": "22-advanced-security",
      "title": "Advanced Security",
      "files": []
    },
    {
      "order": 23,
      "slug": "23-observability-and-debugging",
      "title": "Observability & Debugging",
      "files": []
    },
    {
      "order": 24,
      "slug": "24-api-design-and-contracts",
      "title": "API Design & Contracts",
      "files": []
    },
    {
      "order": 25,
      "slug": "25-web-components",
      "title": "Web Components",
      "files": []
    },
    {
      "order": 26,
      "slug": "26-accessibility-a11y",
      "title": "Accessibility (A11y)",
      "files": []
    },
    {
      "order": 27,
      "slug": "27-build-internals",
      "title": "Build Internals",
      "files": []
    },
    {
      "order": 28,
      "slug": "28-ai-native-dev",
      "title": "AI-Native Dev",
      "files": []
    },
    {
      "order": 29,
      "slug": "29-typescript-advanced",
      "title": "TypeScript (Advanced)",
      "files": []
    }
  ]
};
